version: '3.8'

services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playwright-tests
    working_dir: /app
    volumes:
      - .:/app
    command: ["yarn", "test:docker"]